Repository robotics-laboratory/handy, pull requests merged in 2024-03, with the labels that each got.

#20 CI pipeline
  .clang-tidy
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  .pre-commit-config.yaml
  packages/camera/CMakeLists.txt
Labels: enhancement, CI

#22 Codestyle fix
  .clang-tidy
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  Dockerfile
  README.md
  packages/camera/include/calibration.h
  packages/camera/include/camera.h
  packages/camera/include/camera_status.h
  packages/camera/include/params.h
  packages/camera/launch/camera.yaml
  packages/camera/launch/demo.yaml
  packages/camera/launch/demo_calibration.yaml
  packages/camera/scripts/camera_identifier/src/identifier.cpp
  packages/camera/scripts/rosbag_parser/rosbag_parser.py
  packages/camera/src/calibration.cpp
  packages/camera/src/calibration_main.cpp
  packages/camera/src/camera.cpp
  packages/camera/src/params.cpp
  packages/camera_srvs/CMakeLists.txt
  packages/camera_srvs/package.xml
Labels: fix

#19 Scripts for creating a dataset. DVC support
  .dvc/.gitignore
  .dvc/config
  .gitignore
  datasets/.gitignore
  datasets/annotated_12_02_23.dvc
  datasets/ball_dataset_side_1.dvc
  datasets/ball_dataset_side_2.dvc
  packages/camera/scripts/dataset_creator.py
  packages/camera/scripts/rosbag_parser.py
  packages/camera_identifier/CMakeLists.txt
  packages/camera_identifier/src/identifier.cpp
  requirements.txt
Labels: enhancement

#15 Camera synchronization
  .gitignore
  packages/camera/CMakeLists.txt
  packages/camera/include/camera.h
  packages/camera/include/lock_free_queue.h
  packages/camera/include/params.h
  packages/camera/launch/camera.yaml
  packages/camera/package.xml
  packages/camera/src/camera.cpp
  packages/camera/src/camera_main.cpp
  packages/camera/src/params.cpp
Labels: enhancement

#23 CI fixes
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .yamllint-config.yaml
  Dockerfile
  Makefile
  docker-compose.yaml
  packages/camera/CMakeLists.txt
  packages/camera/launch/bridge.yaml
  packages/camera/launch/calibration.yaml
  packages/camera/launch/camera.yaml
  packages/camera/launch/demo.yaml
  packages/camera/launch/demo_calibration.yaml
  packages/camera/scripts/dataset_creator.py
  packages/camera/scripts/rosbag_parser.py
  packages/camera_identifier/CMakeLists.txt
  packages/camera_srvs/CMakeLists.txt
  pyproject.toml
Labels: enhancement, CI
