Repository robotics-laboratory/handy, pull requests merged in 2024-07, with the labels that each got.

#35 New CI fixes
  .clang-format
  .cmake-format.py
  .pre-commit-config.yaml
  Makefile
  packages/camera/CMakeLists.txt
  packages/camera/src/calibration.cpp
  packages/camera/src/camera.cpp
  packages/camera/src/params.cpp
  packages/camera/test/CMakeLists.txt
  packages/camera_identifier/CMakeLists.txt
  packages/camera_srvs/CMakeLists.txt
  packages/common/CMakeLists.txt
  packages/common/include/lock_free_queue.h
  packages/common/tests/CMakeLists.txt
  pyproject.toml
Labels: CI, fix

#33 Deleted ROS2-related files
  packages/camera/CMakeLists.txt
  packages/camera/package.xml
  packages/camera/scripts/binary_parser.py
  packages/camera/scripts/dataset_creator.py
  packages/camera/scripts/rosbag_parser.py
  packages/camera_srvs/CMakeLists.txt
  packages/camera_srvs/package.xml
  packages/camera_srvs/srv/CalibrationCommand.srv
  packages/common/CMakeLists.txt
  packages/common/include/lock_free_queue.h
  packages/common/package.xml
  packages/common/tests/CMakeLists.txt
  packages/common/tests/src/test.cpp
Labels: fix

#36 Remove --ffast-math and add autocomplete
  Dockerfile
  docker-compose.yaml
Labels: container, fix

#37 Update readme
  README.md
Labels: documentation

#32 Triangulation and visualisation
  packages/camera/CMakeLists.txt
  packages/camera/include/params.h
  packages/camera/include/triangulation.h
  packages/camera/scripts/mask_to_centroid.py
  packages/camera/scripts/triangulation_to_mcap.py
  packages/camera/src/params.cpp
  packages/camera/src/triangulation.cpp
Labels: enhancement
